resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:d7a24329d2a9fc9a762b9a5f49d319ac65e4c3f4d16f5dd2e3ddee11bf96f041
  name: quay.io/bluesman/quinoa-wind-turbine
